### ISSUE TITLE
Proposed changes to getProductForTag(…) function

### ISSUE THREAD

**Issue by warpling** [themonetizr/monetizr-ios-sdk#1]
The function name doesn't fully reflect what this function does. I'd propose an alternate signature like `    public func showProduct(_ tag: String, presenter: UIViewController? = nil, presentationStyle: UIModalPresentationStyle? = nil, completionHandler: @escaping (Bool, Error?, Product?) -> Void)`

Additionally I think it makes sense that presentationStyle is an optional parameter but think the default should be `.automatic` for iOS 13 and perhaps `.overCurrentContext` is not? This gives iOS 13 players the new default panel style which developers can opt out of it they don't want the default system behavior.

**Comment by armandsavotins** [comment]
Changes made in af31362c3398d0be6ab80f0a19c2beab8e657587
