### ISSUE TITLE
Build errors related to McPickerBarButtonItem and Xcode 12?

### ISSUE THREAD

**Issue by warpling** [themonetizr/monetizr-ios-sdk#12]
https://github.com/kmcgill88/McPicker-iOS/issues/66

**Comment by cerupcat** [comment]
@warpling , with your version I'm getting "Cannot override a Self return type with a non-Self return type" with Xcode 12 Beta 4.

**Comment by kmcgill88** [comment]
Closing in favor of #66

**Comment by armandsavotins** [comment]
It appears to be solved with McPicker 3.x

**Comment by kmcgill88** [comment]
@armandsavotins I did indeed correct this in v3. Also requires xcode 12.
