### ISSUE TITLE
Localization Breaks Base App

### ISSUE THREAD

**Issue by parrots** [themonetizr/monetizr-ios-sdk#16]
It appears as though Monetizr uses a localizable string file named the same as the default. In practice, that means that Monetizr's strings file will be copied into the main app bundle, usually overriding or worse corrupting the app's default localization strings file.

It appears as though the common practice is to have the strings file in a framework be named after the framework, ex: MonetizrLocalizable.strings.

See: https://github.com/CocoaPods/CocoaPods/issues/1653#issuecomment-239326155

**Comment by armandsavotins** [comment]
Fixed in version 3.5.7
