### ISSUE TITLE
Recommend lowercasing enum values like ProductViewControllerTheme

### ISSUE THREAD

**Issue by warpling** [themonetizr/monetizr-ios-sdk#2]
This would go along with the modern Swift API style :)

**Comment by armandsavotins** [comment]
Change in 3f4a083722e81a6a5864eed13a38f0b1aec8bc3a

**Comment by warpling** [comment]
.dark and .default would be in line with standard style. The name of the ‭‭‭‭enum type itself is fine!

**Comment by armandsavotins** [comment]
`public enum ProductViewControllerTheme {
      case default
      case black
    }`
Like that it would be along with the modern Swift API style?

**Comment by armandsavotins** [comment]
@warpling take a look at that 6b5f096ad421a34c13763c414e95888967047614

**Comment by armandsavotins** [comment]
Some adjustments also made in 52d4f3ab57dcd64085c92f71381b1cd352f168b9

**Comment by warpling** [comment]
Great! Personally I might go with `.dark` and `.light` to match the system and be more color agnostic but not terrible important :)

**Comment by warpling** [comment]
Is there a reason there's a picker library included in the library now?

**Comment by armandsavotins** [comment]
Picker should be only in Sample app and used to chose some theme

**Comment by armandsavotins** [comment]
Here is what's included in pod  

s.source_files = 'Monetizr-SDK/*'
  s.resources = ['Monetizr-SDK/*.lproj', 'Monetizr-SDK/Assets/*']

  s.framework = "UIKit"
  s.framework = "PassKit"
  s.dependency 'Alamofire', '~> 4.0'
  s.dependency 'ImageSlideshow/Alamofire'
  s.dependency 'ImageSlideshow', '~> 1.8'
  s.dependency 'Stripe/ApplePay'

**Comment by armandsavotins** [comment]
I guess @nauris-monetizr could do some comments about theme naming. ".base" is chosen to be kind a default theme which adopts to Dark/Light modes, and ".black" (suggested by Monetizr team) is used for the other theme which does not adopts to Dark/Light modes.

**Comment by warpling** [comment]
Sorry @armandsavotins! Just saw that the picker was just for the sample app—my bad.

And that's good to know about the themes! I had no idea `.base` would do that. Perhaps `.system` would be a clearer name? With a little bit of documentation I think that'd make that clearer for people who want that preference? In that case it would also make sense to have `.light` for those who need/want to force the view into a lighter theme?

**Comment by armandsavotins** [comment]
Yes .system might sound better, will change. ".light" might be an option alongside with ".dark". Existing".black" is a bit different form system dark.

@nauris-monetizr Might be you can make comments and description about themes in Readme!?

**Comment by armandsavotins** [comment]
In latest version .base theme renamed to .system. Some info about themes added to Readme.

**Comment by armandsavotins** [comment]
Monetizr (3.2.2) successfully published
 📅  October 23rd, 00:15
 🌎  https://cocoapods.org/pods/Monetizr

**Comment by warpling** [comment]
Nice!
