### ISSUE TITLE
Setting language vs locale

### ISSUE THREAD

**Issue by warpling** [themonetizr/monetizr-ios-sdk#4]
Currently the `setLanguage(language:) function is a bit misleading since it actually expects a locale code like `en_US` versus just a language code like `en`.

I think it makes sense to use locale codes since we want to support language variants like `pt-PT` and `pt-BR` (Portuguese Portuguese and Brazilian Portuguese respectively) but the function name should reflect this so developer pass the right thing. 

Perhaps it is also worth supporting passing along the preferred languages array as well, which HTTP already supports fairly well, in order to allow us to fallback on languages (if Brazilian Portuguese isn't available it'd be better to fallback on Portuguese Portuguese than American English). [This](https://nshipster.com/locale/) is a great, short read on the matter!

One other small thing would be to use `_` in the function signature too so language isn't `redundantly` mentioned ;) So something like `setLangugages(_ language:)` and `setPreferredLangugages(_ preferredLanguages:)`

**Comment by armandsavotins** [comment]
That actually will depend on API. What will be supported. For now API reference contains only "language" = "en" in the cal for product.
@nauris-monetizr  you should define what will API support and SDK can be adopted.

**Comment by nauris-monetizr** [comment]
Current intent is to support locales and languages as proposed above in an upcoming version. No timeline for that is available though.

**Comment by warpling** [comment]
Got it. So for now we should only pass a language code like "en" or "pr"?

**Comment by armandsavotins** [comment]
As far as I know language not really working at the moment and since it optional it could be left unset. @martins-jansevskis can make more comments on that.

**Comment by warpling** [comment]
Got it. I will leave it unset for now and will leave this issue open

**Comment by armandsavotins** [comment]
I guess since release 3.3.2 this is no more issue
