### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by warpling** [themonetizr/monetizr-ios-sdk#5]
The accessibilit is pretty solid! A few small things I noticed currently missing to make it top-notch:

## VoiceOver
- [x] Support `accessibilityPerformEscape()` to dismiss the product view and quantity/size picker (same action as the close button) when an escape gesture is made or called out using Voice Control. 
- [x] Mark items in the image carousel as `accessibilityElement`s and add the `accessibilityTrait` `.image` if possible. This allows blind users to ask the system to attempt to describe what is shown but at the very least lets people know that the picker (which is supported by VoiceOver) is in fact changing something (currently the images aren't selectable by Voiceover).
- [x] on `viewDidAppear` move focus to the most important element. Right now when the product view opens VoiceOver first reads "close button". Call `UIAccessibility.post(notification: .screenChanged, argument:label)` to set the focus to something like the product title or the selected quantity or size when the size picker is presented!

## Smart Invert
- [x] Mark images in the carousel's `accessibilityIgnoresInvertColors` property to true so they don't invert when smart invert is enabled! People using this setting expect most things to invert but not images which then become pretty weird looking.

## Voice Control
- [x] Quantity/Size picker isn't choose able by Voice Control. I think this has to do with the view missing an `accessibilityLabel`? As a larger change I would probably mark the entire containing bar view as an `accessibilityElement` and set it's `accessibilityLabel` to the "select quantity" text for now and it's `accessibilityValue` to the "5 decals" text while giving it an `accessibilityHint` along the lines of "tap to change" and an `accessibilityTrait` of `.button`.

Let me know if you need a hand or have questions with any of these! I'm happy to help :)

**Comment by armandsavotins** [comment]
p.s. for the image carousel https://github.com/zvonicek/ImageSlideshow is used. We can ask author to make described changes or we should fork and make changes ourselves.

**Comment by armandsavotins** [comment]
Part of the suggested things is available in version 3.2.4 8504cecc2f1a36f8a6de4614cb9df9bee16bd753

**Comment by warpling** [comment]
Awesome to see progress on these! I'll check them out soon. Was hoping to have time to make an accessibility PR to ImageSlideshow but haven't been able to yet.

**Comment by armandsavotins** [comment]
We have asked author to do some Accessibility enhancements - https://github.com/zvonicek/ImageSlideshow/issues/356 If there will be no response in  some reasonable time frame most likely we will make update ourselves as well.

**Comment by armandsavotins** [comment]
Waiting on https://github.com/zvonicek/ImageSlideshow/pull/367

**Comment by warpling** [comment]
Fantastic work
