### ISSUE TITLE
Build Warning

### ISSUE THREAD

**Issue by parrots** [themonetizr/monetizr-ios-sdk#8]
`country-data.json` is in the Compile Sources build phase, which generates a compiler warning. This file should be removed from this phase.

```
no rule to process file 'App/Pods/Monetizr/Monetizr-SDK/country-data.json' of type 'text.json' for architecture 'arm64'
```

**Comment by armandsavotins** [comment]
Should be fixed since version 3.5.1

**Comment by armandsavotins** [comment]
@parrots do you still have this issue?

**Comment by parrots** [comment]
@armandsavotins I don't see the issue anymore, thanks
